<?php
/**
 * @file
 * A block module that displays the multi diagram navigation widget.
 
 /**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function mdn_help($path, $arg) {
  switch ($path) {
    case "admin/help#mdn":
      return '<p>' . t("Widget to show diagrams") . '</p>';
      break;
  }
} 

/**
 * Implements hook_block_info().
 */
function mdn_block_info() {
  $blocks['mdn'] = array(
    // The name that will appear in the block list.
    'info' => t('mdn'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
    $blocks['mdnNodeViewer'] = array(
    // The name that will appear in the block list.
    'info' => t('mdnNodeViewer'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

function mdn_block_view($delta = '') {
  switch ($delta) {
    case 'mdn':
      $block['subject'] = t('mdn');
      if (user_access('access content')) {
       $block['content'] = get_mdn(); //"<div id='mdn'><p>Test block</p></div>";
      }
      break;
	  
    case 'mdnNodeViewer':
      $block['subject'] = t('mdn Node Viewer');
      if (user_access('access content')) {
       $block['content'] = "<div id='mdnNodeViewer'><p>default node will be displayed</p></div>"; //"<div id='mdn'><p>Test block</p></div>";
	  }
	  break;
 }
 return $block;
}

function get_mdn() {
 // drupal_add_js(drupal_get_path('module', 'mdn') .'/js/jquery-1.11.1.min.js');
 // drupal_add_js(drupal_get_path('module', 'mdn') .'/js/jquery.contextMenu.js');
 // drupal_add_js(drupal_get_path('module', 'mdn') .'/js/jquery.ui.position.js');
 // drupal_add_css(drupal_get_path('module', 'mdn') . '/jquery.contextMenu.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
 
  // include our custom Raphael extension
 // drupal_add_js(drupal_get_path('module', 'mdn') . '/js/raphael.bar.js');
 
  // include our Drupal behaviors
 drupal_add_js(drupal_get_path('module', 'mdn') . '/mdnjs.js');
 
  $graph_data = array(
    'hello' => array(
      'current' => 4,
      'total' => 7
    )
  );
 
  drupal_add_js($graph_data, 'setting');
 
  /*
     Check the default layout (one, two, three, or four diagrams) (two for now)
	 Retrieve the required # of default SVGs (SVG markup in DOM and SVG record in the database)
	 iterate over default SVGs (the first few)
	    if SVG_hide_elements = true // SVG elements are on top of image 
		   change css to hide elements
		else
           nothing
        
     		
	 embed the default SVGs in the main mdn html 
	    two divs for now 
		required buttons
	    load any required CSS (maybe for diagram browser)
	 
	-----------------------
    I need following configuration info.
	- default layout
	
	For every SVG
	- default SVG true/false 
	- hide elements true/false 
    - highlight color
    - select color
    - hover color	
  */
  
  
  $svg_js = file_get_contents(drupal_get_path('module', 'mdn') . '/SVGjs.js'); 
  
  $file = file_load(9);
  $contents = file_get_contents($file->uri);
  $pos = strrpos($contents, '</svg', -1);
    
  if ($pos === false){
	$contents2 = "SVG file is not valid. Please make sure to load diagrams in SVG format";
	}
  else{
    $contents2 = substr_replace($contents, $svg_js, $pos, 0);  	 
  }

  $file = file_load(8);
  $contents = file_get_contents($file->uri);
  $pos = strrpos($contents, '</svg', -1);
    
  if ($pos === false){
	$contents2 = $contents2 . '<br>' . "SVG file is not valid. Please make sure to load diagrams in SVG format";
	}
  else{
    $contents3 = substr_replace($contents, $svg_js, $pos, 0);
    $contents2 = $contents2 . '<br>' . $contents3;	
    }
   
   /*
   Possible design 
   2 divs one over the other and a space for buttons
   zoom button will be in the svg
   
   */

	return  $contents2;  
  //return  "<div id='mdn'><p>hello</p></div>";
  
}

function mdn_menu() {
  $items['mdn/get/ajax'] = array(
    'page callback' => 'mdn_get_node',
    'page arguments' => array(3),
	'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
	 'delivery callback' => 'mdn_magic', 
  );
  return $items;
}

function mdn_get_node($nid) {
  $node = node_load($nid);
  return node_view($node, 'teaser');
  //return "<p>new stuff</p>";
}

function mdn_magic($page_callback_result) {
  // Only render content
  $content = drupal_render($page_callback_result);

  // Add CSS ans JS files, add some markup
  //$html = '<html><head><title></title>' . drupal_get_css() . drupal_get_js() . '</head><body class="jquery-ajax-load">' . $content . '</body></html>';
  print $content;

  // Perform end-of-request tasks.
  //drupal_page_footer();
}
/**
 * Implementation of hook_theme().
 */
/*
 function mdn_theme($existing, $type, $theme, $path) {
  return array(
    'mdn' => array(
      'variables' => array(),
    ),
  ); // not sure if variables is correct or not, need to read about theming
}


function theme_mdn() {
  return "<div id='mdn'><noscript>Enable JavaScript to see this awesome graph.</noscript></div>";
}
*/